-- Add columns for intermediate course generation artifacts
ALTER TABLE intello_study_sessions
ADD COLUMN extracted_knowledge JSONB DEFAULT NULL,
ADD COLUMN educational_content JSONB DEFAULT NULL,
ADD COLUMN expanded_knowledge TEXT DEFAULT NULL;

COMMENT ON COLUMN intello_study_sessions.extracted_knowledge IS 'Structured knowledge extracted from resources (Stage 1)';
COMMENT ON COLUMN intello_study_sessions.educational_content IS 'Detailed educational content generated from knowledge base (Stage 1.5)';
COMMENT ON COLUMN intello_study_sessions.expanded_knowledge IS 'Expanded knowledge text generated by AI (Stage 0.5)';
